### ISSUE TITLE
Cannot import ComfyUI-Malefish-Custom-Scriptsmodule for custom nodes: 'wildcards' 

### ISSUE THREAD

**Issue by xia-huang-411303** [ParmanBabra/ComfyUI-Malefish-Custom-Scripts#3]
```bash
Traceback (most recent call last):
  File "/mnt/e/LSY/comfyui/nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/e/LSY/comfyui/custom_nodes/ComfyUI-Malefish-Custom-Scripts/__init__.py", line 3, in <module>
    from .py.conditioning.random_prompt import *
  File "/mnt/e/LSY/comfyui/custom_nodes/ComfyUI-Malefish-Custom-Scripts/py/conditioning/random_prompt.py", line 15, in <module>
    Path(folder_paths.get_folder_paths("wildcards")[0]))
  File "/mnt/e/LSY/comfyui/folder_paths.py", line 137, in get_folder_paths
    return folder_names_and_paths[folder_name][0][:]
KeyError: 'wildcards'
```

**Comment by koking0** [comment]
me too

**Comment by koking0** [comment]
I'm also encountering this issue. The traceback provided is very similar to what I'm experiencing. Any insights or workarounds would be greatly appreciated!

```python
Traceback (most recent call last):
  File "/ssd2/ComfyUI/nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/ssd2/ComfyUI/custom_nodes/ComfyUI-Malefish-Custom-Scripts/__init__.py", line 3, in <module>
    from .py.conditioning.random_prompt import *
  File "/ssd2/ComfyUI/custom_nodes/ComfyUI-Malefish-Custom-Scripts/py/conditioning/random_prompt.py", line 15, in <module>
    Path(folder_paths.get_folder_paths("wildcards")[0]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/ComfyUI/folder_paths.py", line 212, in get_folder_paths
    return folder_names_and_paths[folder_name][0][:]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'wildcards'
```
